### ISSUE TITLE
Publish as @hapipal/hecks

### ISSUE THREAD

**Issue by Nargonath** [devinivy/hecks#15]
Shouldn't we publish this package under the `@hapipal` namespace as you did for other packages @devinivy?

**Comment by devinivy** [comment]
It is published, but kept on its own branch for the time being:
https://github.com/hapipal/hecks/blob/v3/package.json
https://www.npmjs.com/package/@hapipal/hecks

Also relates to #10.  I will merge these branches to the main branch once the whole org is converted, the website is updated, etc.

**Comment by Nargonath** [comment]
I just noticed you already published it under the `@hapipal` namespace: https://github.com/hapipal/hecks/issues/10. However shouldn't we change the name in the package.json to be `@hapipal/hecks` too?

**Comment by devinivy** [comment]
Yes, the trick is that v3 is on a branch 👍

**Comment by Nargonath** [comment]
haha damn we just posted at the same time. Sorry for the stupid question, didn't notice the v3 branch. My bad. 😅
